export const seedCategories = [
  { name: '语文', emoji: '📖', bgColor: '#EDE9FE', sortOrder: 1 },
  { name: '数学', emoji: '🔢', bgColor: '#DBEAFE', sortOrder: 2 },
  { name: '物理', emoji: '⚛️', bgColor: '#E0F2FE', sortOrder: 3 },
  { name: '化学', emoji: '🧪', bgColor: '#D1FAE5', sortOrder: 4 },
  { name: '外语', emoji: '🌍', bgColor: '#FEF3C7', sortOrder: 5 },
  { name: '音乐', emoji: '🎵', bgColor: '#FCE7F3', sortOrder: 6 },
  { name: '舞蹈', emoji: '💃', bgColor: '#F3E8FF', sortOrder: 7 },
  { name: '编程', emoji: '💻', bgColor: '#E0E7FF', sortOrder: 8 },
]

export const seedCourses = [
  {
    sortOrder: 1,
    title: '徐汇区小学数学思维提升班',
    subtitle: '逻辑训练 · 举一反三',
    tags: ['思维训练', '小班教学'],
    price: 5280,
    originalPrice: 5980,
    coverBg: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    coverUrl: '/assets/courses/course-math.png',
    detailImageUrl: '/assets/courses/course-math.png',
    categoryName: '数学',
    city: '上海',
    district: '徐汇区',
    address: '徐汇区漕溪北路 88 号 3 层',
    storeName: '智学教育·徐汇校区',
    institutionName: '智学教育',
    targetAudience: '儿童',
    brandName: '智学教育',
    memberPrice: 129,
    ageRange: '7-12岁',
    rating: 4.8,
    enrollCount: 96,
    sales: 142,
    reviewCount: 12,
    facilityTags: ['教室明亮', '多媒体教学', '老师专业', '地铁直达'],
    serviceTags: ['评价', '预约', '咨询', '试听'],
    policyTags: ['随时退', '过期自动退'],
    featureTags: ['数学', '思维训练', '小学', '奥数预备'],
    overview: [
      { label: '课时', value: '36 课时' },
      { label: '人数', value: '8 人/班' },
      { label: '类型', value: '线下课程' },
      { label: '适合人群', value: '7-12 岁' },
      { label: '上课地点', value: '徐汇区漕溪北路 88 号' },
      { label: '课程形式', value: '小班教学' },
      { label: '有效期', value: '365 天' },
      { label: '消课方式', value: '一课一消' },
    ],
    syllabus: [
      { phase: '基础', content: '数感培养、四则运算、应用题建模', time: '周六 09:00-10:30' },
      { phase: '进阶', content: '几何直观、逻辑推理、综合应用', time: '周六 10:40-12:10' },
      { phase: '拓展', content: '竞赛题型、思维拓展、错题复盘', time: '周日 14:00-15:30' },
    ],
    description:
      '系统训练小学数学思维与解题能力，采用小班制教学，注重举一反三与逻辑推理。课程涵盖数感培养、应用题建模与竞赛预备，帮助学员建立扎实的数学基础。',
  },
  {
    sortOrder: 2,
    title: '浦东新区阅读理解与写作精品课',
    subtitle: '夯实基础 · 提升表达',
    tags: ['阅读写作', '名师指导'],
    price: 4680,
    originalPrice: 5280,
    coverBg: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    coverUrl: '/assets/courses/course-chinese.png',
    detailImageUrl: '/assets/courses/course-chinese.png',
    categoryName: '语文',
    city: '上海',
    district: '浦东新区',
    address: '浦东新区张杨路 588 号 2 层',
    storeName: '文启优学培训中心',
    institutionName: '文启优学培训中心',
    targetAudience: '儿童',
    brandName: '文启优学',
    memberPrice: 129,
    ageRange: '8-14岁',
    rating: 4.9,
    enrollCount: 118,
    sales: 198,
    reviewCount: 18,
    facilityTags: ['阅读专区', '设施齐全', '老师专业', '停车方便'],
    serviceTags: ['评价', '预约', '咨询', '试听'],
    policyTags: ['随时退', '过期自动退'],
    featureTags: ['语文', '阅读', '写作', '青少年'],
    overview: [
      { label: '课时', value: '40 课时' },
      { label: '人数', value: '10 人/班' },
      { label: '类型', value: '线下课程' },
      { label: '适合人群', value: '8-14 岁' },
      { label: '上课地点', value: '浦东新区张杨路 588 号' },
      { label: '课程形式', value: '小班教学' },
      { label: '有效期', value: '365 天' },
      { label: '消课方式', value: '一课一消' },
    ],
    syllabus: [
      { phase: '阅读', content: '精读技巧、信息提取、文本分析', time: '周六 09:00-10:30' },
      { phase: '写作', content: '素材积累、结构搭建、表达润色', time: '周六 10:40-12:10' },
      { phase: '综合', content: '古诗文鉴赏、综合运用、模拟测评', time: '周日 14:00-15:30' },
    ],
    description:
      '针对 8-14 岁学员，系统提升阅读理解与写作能力。课程涵盖精读技巧、写作表达与古诗文鉴赏，帮助学员夯实语文基础、提升综合素养。',
  },
  {
    sortOrder: 3,
    title: '静安区初中物理趣味实验班',
    subtitle: '动手实践 · 理解原理',
    tags: ['实验教学', '竞赛预备'],
    price: 5580,
    originalPrice: 6280,
    coverBg: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
    coverUrl: '/assets/courses/course-physics.png',
    detailImageUrl: '/assets/courses/course-physics.png',
    categoryName: '物理',
    city: '上海',
    district: '静安区',
    address: '静安区南京西路 1266 号 B1 层',
    storeName: '启物科学实验室',
    institutionName: '启物科学实验室',
    targetAudience: '青少年',
    brandName: '启物科学',
    memberPrice: 129,
    ageRange: '11-15岁',
    rating: 4.7,
    enrollCount: 72,
    sales: 108,
    reviewCount: 9,
    facilityTags: ['专业实验室', '安全防护', '器材齐全', '交通便利'],
    serviceTags: ['评价', '预约', '咨询', '试听'],
    policyTags: ['随时退', '过期自动退'],
    featureTags: ['物理', '实验', '初中', '科学探究'],
    overview: [
      { label: '课时', value: '32 课时' },
      { label: '人数', value: '6 人/班' },
      { label: '类型', value: '线下课程' },
      { label: '适合人群', value: '11-15 岁' },
      { label: '上课地点', value: '静安区南京西路 1266 号' },
      { label: '课程形式', value: '实验 + 讲授' },
      { label: '有效期', value: '365 天' },
      { label: '消课方式', value: '一课一消' },
    ],
    syllabus: [
      { phase: '力学', content: '力与运动、压强浮力、简单机械实验', time: '周六 14:00-15:30' },
      { phase: '光学', content: '光的反射折射、透镜成像、光学仪器', time: '周六 15:40-17:10' },
      { phase: '电学', content: '电路基础、欧姆定律、电功率应用', time: '周日 09:00-10:30' },
    ],
    description:
      '以趣味实验带动物理概念理解，涵盖力学、光学与电学核心知识点。小班实验教学，注重动手操作与科学探究，帮助学员建立物理直觉与解题能力。',
  },
  {
    sortOrder: 4,
    title: '黄浦区化学启蒙实验室',
    subtitle: '安全实验 · 激发兴趣',
    tags: ['趣味化学', '动手操作'],
    price: 4980,
    originalPrice: 5680,
    coverBg: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    coverUrl: '/assets/courses/course-chemistry.png',
    detailImageUrl: '/assets/courses/course-chemistry.png',
    categoryName: '化学',
    city: '上海',
    district: '黄浦区',
    address: '黄浦区淮海中路 300 号 5 层',
    storeName: '元素探索教育',
    institutionName: '元素探索教育',
    targetAudience: '青少年',
    brandName: '元素探索',
    memberPrice: 129,
    ageRange: '10-14岁',
    rating: 4.8,
    enrollCount: 58,
    sales: 86,
    reviewCount: 7,
    facilityTags: ['标准实验室', '通风安全', '专业指导', '市中心'],
    serviceTags: ['评价', '预约', '咨询', '试听'],
    policyTags: ['随时退', '过期自动退'],
    featureTags: ['化学', '实验', '启蒙', '科学素养'],
    overview: [
      { label: '课时', value: '28 课时' },
      { label: '人数', value: '6 人/班' },
      { label: '类型', value: '线下课程' },
      { label: '适合人群', value: '10-14 岁' },
      { label: '上课地点', value: '黄浦区淮海中路 300 号' },
      { label: '课程形式', value: '实验 + 讲授' },
      { label: '有效期', value: '365 天' },
      { label: '消课方式', value: '一课一消' },
    ],
    syllabus: [
      { phase: '入门', content: '物质变化、元素周期、安全操作规范', time: '周六 10:00-11:30' },
      { phase: '实验', content: '酸碱反应、氧化还原、常见气体制备', time: '周六 13:30-15:00' },
      { phase: '应用', content: '生活化学、环境化学、综合探究项目', time: '周日 10:00-11:30' },
    ],
    description:
      '在安全规范的实验室环境中开展化学启蒙教学，通过趣味实验理解物质变化与化学反应。课程注重科学素养培养，激发学员对化学的兴趣与探究精神。',
  },
  {
    sortOrder: 5,
    title: '长宁区少儿英语口语精品课',
    subtitle: '情景对话 · 外教互动',
    tags: ['口语', '外教'],
    price: 4580,
    originalPrice: 5180,
    coverBg: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    coverUrl: '/assets/courses/course-english.png',
    detailImageUrl: '/assets/courses/course-english.png',
    categoryName: '外语',
    city: '上海',
    district: '长宁区',
    address: '长宁区延安西路 1262 号 4 层',
    storeName: '环球少儿英语',
    institutionName: '环球少儿英语',
    targetAudience: '儿童',
    brandName: '环球少儿',
    memberPrice: 129,
    ageRange: '5-12岁',
    rating: 4.6,
    enrollCount: 84,
    sales: 127,
    reviewCount: 15,
    facilityTags: ['外教课堂', '情景教室', '小班互动', '地铁沿线'],
    serviceTags: ['评价', '预约', '咨询', '试听'],
    policyTags: ['随时退', '过期自动退'],
    featureTags: ['英语', '口语', '外教', '少儿'],
    overview: [
      { label: '课时', value: '48 课时' },
      { label: '人数', value: '8 人/班' },
      { label: '类型', value: '线下课程' },
      { label: '适合人群', value: '5-12 岁' },
      { label: '上课地点', value: '长宁区延安西路 1262 号' },
      { label: '课程形式', value: '外教 + 中教' },
      { label: '有效期', value: '365 天' },
      { label: '消课方式', value: '一课一消' },
    ],
    syllabus: [
      { phase: '启蒙', content: '自然拼读、日常词汇、简单对话', time: '周三 18:00-19:00' },
      { phase: '进阶', content: '情景口语、听力训练、课堂表达', time: '周六 10:00-11:30' },
      { phase: '拓展', content: '主题阅读、演讲展示、跨文化交际', time: '周日 14:00-15:30' },
    ],
    description:
      '外教互动 + 情景对话教学模式，帮助少儿建立英语口语自信。课程涵盖自然拼读、日常交际与主题表达，在轻松氛围中提升听说能力。',
  },
  {
    sortOrder: 6,
    title: '静安区中国舞启蒙课',
    subtitle: '优美体态从小培养',
    tags: ['舞蹈基础', '4-8岁'],
    price: 2880,
    originalPrice: 3280,
    coverBg: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    coverUrl: '/assets/courses/course-4.jpg',
    detailImageUrl: '/assets/courses/course-4.jpg',
    categoryName: '舞蹈',
    city: '上海',
    district: '静安区',
    address: '静安区昌平路 710 号 2 层',
    storeName: '舞动童年艺术中心',
    institutionName: '舞动童年艺术中心',
    targetAudience: '儿童',
    brandName: '舞动童年',
    memberPrice: 99,
    ageRange: '4-8岁',
    rating: 4.9,
    enrollCount: 52,
    sales: 76,
    reviewCount: 11,
    facilityTags: ['舞蹈教室', '镜墙齐全', '老师专业', '家长休息区'],
    serviceTags: ['评价', '预约', '咨询', '试听'],
    policyTags: ['随时退', '过期自动退'],
    featureTags: ['舞蹈', '中国舞', '启蒙', '体态培养'],
    overview: [
      { label: '课时', value: '24 课时' },
      { label: '人数', value: '12 人/班' },
      { label: '类型', value: '线下课程' },
      { label: '适合人群', value: '4-8 岁' },
      { label: '上课地点', value: '静安区昌平路 710 号' },
      { label: '课程形式', value: '小班教学' },
      { label: '有效期', value: '365 天' },
      { label: '消课方式', value: '一课一消' },
    ],
    syllabus: [
      { phase: '基础', content: '体态训练、基本手位脚位、节奏感培养', time: '周六 09:30-10:30' },
      { phase: '组合', content: '简单舞蹈组合、队形变化、音乐配合', time: '周六 10:40-11:40' },
      { phase: '展示', content: '成品舞排练、舞台礼仪、汇报演出', time: '期末汇演' },
    ],
    description:
      '针对 4-8 岁儿童的中国舞启蒙课程，注重优美体态与节奏感培养。通过基本功训练与舞蹈组合学习，帮助学员建立艺术感知与舞台自信。',
  },
]

export const seedBanners = [
  {
    title: '暑期课程嘉年华',
    subtitle: '精选课程 限时优惠',
    imageUrl: '/assets/banners/banner-1.jpg',
    sortOrder: 1,
  },
  {
    title: '名师一对一',
    subtitle: '专属辅导 快速提分',
    imageUrl: '/assets/banners/banner-2.jpg',
    sortOrder: 2,
  },
  {
    title: '全学科畅学',
    subtitle: '语数外物化 一站搞定',
    imageUrl: '/assets/banners/banner-3.jpg',
    sortOrder: 3,
  },
]
