-- AlterTable
ALTER TABLE "Course" ADD COLUMN     "address" TEXT,
ADD COLUMN     "ageRange" TEXT,
ADD COLUMN     "brandName" TEXT,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "detailImageUrl" TEXT,
ADD COLUMN     "district" TEXT,
ADD COLUMN     "enrollCount" INTEGER,
ADD COLUMN     "facilityTags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "featureTags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "institutionName" TEXT,
ADD COLUMN     "memberPrice" DECIMAL(10,2),
ADD COLUMN     "originalPrice" DECIMAL(10,2),
ADD COLUMN     "overview" JSONB,
ADD COLUMN     "policyTags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "rating" DOUBLE PRECISION,
ADD COLUMN     "reviewCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "sales" INTEGER,
ADD COLUMN     "serviceTags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "sortOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "storeName" TEXT,
ADD COLUMN     "syllabus" JSONB,
ADD COLUMN     "targetAudience" TEXT;
